codecov:
  require_ci_to_pass: yes
  coverage:
    status:
      project:
        default:
          target: auto
          precision: 2
        comment:
          layout: "header, diff, files"
    files:
      - ./target/site/jacoco.exec