version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bank-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin123
    ports:
      - 1433:1433
    volumes:
      - dbdata:/var/opt/mssql
volumes:
  dbdata: