version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin123
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
  app:
    build:
      context: .
      dockerfile: deploy.dockerfile
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: mvn clean test
    ports:
      - 8080:8080