name: bank CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build-and-test:
      runs-on: ubuntu-latest
            
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get host IP address
        id: get_host_ip
        run: echo "::set-output name=host_ip::$(curl -s https://ipinfo.io/ip)"

      - name: Set up Docker Compose
        run: |
          export MSSQL_HOST=${{ steps.get_host_ip.outputs.host_ip }}
          echo $MSSQL_HOST
          cd Bank
          docker-compose up -d
          sleep 30
          sed -i "s|jdbc:sqlserver://localhost:1433;|jdbc:sqlserver://$MSSQL_HOST:1433;|g" src/main/resources/application.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and test
        run: |
          cd Bank
          mvn clean test
      
    codecov:
      needs: build-and-test
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
