name: bank CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build-and-test:
      runs-on: ubuntu-latest

      steps:
      - name: Set up database
        run: |
          docker run --name bankDatabase -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=admin123" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest
          sleep 10
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and test
        run: mvn clean test
      
    codecov:
      needs: build-and-test
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Upload coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
