name: build

on:
  push:
    branches: [ main ]
    paths: [ '**.java', '.github/workflows/jacoco.yml', 'pom.xml' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jacoco-java-maven:

    runs-on: ubuntu-latest
    
    steps:
    - name: Set up database
      run: |
        docker run --name bankDatabase -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=admin123" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest
        sleep 10
        docker start bankDatabase
        
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Connect to database
      run: docker exec -i bankDatabase /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P admin123 -Q "CREATE DATABASE mydatabase;"

    - name: Build with Maven
      run: |
        cd Bank
        mvn clean test

    - name: Generate Jacoco report
      run: mvn jacoco:report

    - name: Start jacoco-badge-generator
      run: |
        docker run --name jacoco-badge-generator -v "${PWD}/target/site/jacoco:/jacoco" cicirello/jacoco-badge-generator@v2 \
        "/jacoco/jacoco.csv" "badges" "jacoco.svg" "branches.svg" "true" "true" "fail" "0" "0" "false" "false" \
        "100 90 80 70 60 0" "#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44" "false" "false" "jacoco.json" "branches.json" \
        "true" "coverage-summary.json" "coverage" "branches"

    - name: Add badge to README
      run: |
        echo "[![Coverage](./badges/jacoco.svg)](./target/site/jacoco/index.html)" >> README.md
        echo "[![Branches](./badges/branches.svg)](./target/site/jacoco/index.html)" >> README.md
